name: CI

on:
  push:
    branches: 
      - main
      - github/actions
    paths:
      - sample-python-web-app/**
      - .github/workflows/CI.yml

env:
  AWS_REGION: ap-northeast-1 # your AWS region
  ECR_REPOSITORY: dev/practice # your ECR repository name
  # TF_S3_BACKEND_BUCKET: my-tf-backend-bucket # S3 bucket for Terraform state
  # TF_VAR_FARGATE_IMAGE: "" # Docker image for Fargate service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        # if: github.ref == 'refs/heads/github/actions'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./sample-python-web-app/Dockerfile
          push: true
          tags: 996109426400.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Update terraform.tfvars
        run: |
          sed -i '' "s/^image_tag.*/image_tag = \"${{ github.sha }}\"/" ./terraform/composition/dev/terraform.tfvars    
    

      # - name: Commit and push changes
      #   run: |
      #     git config --global user.email "you@example.com"
      #     git config --global user.name "Your Name"
      #     git commit -am "Update Fargate service image"
      #     git push

